### PR TITLE
addr reuse & socket connection abnormal 

### PR DESCRIPTION
**Pull request by xiaoyu-ebox**
1.fixed the problem of add reuse
2.fixed the problem of abnormal exit of socket connection
3.adjust log print

### CODE REVIEW

**Comment by xiaoyu-ebox** [comment]
According to my test, after adding socket exception handling, the PIN number is not affected for 2 minutes.

**Comment by homeworkc** [comment]
Why do we need to reuse idrsock? Isn't it the case where player 1 and player 2 get another port to connect to this port?

**Comment by xiaoyu-ebox** [comment]
because when d2. Py crashes due to an abnormal condition or normally quits, reboot all.sh immediately, and reuse addr will appear if the phone is also connected immediately.

**Comment by homeworkc** [comment]
Oh I see. That makes sense.

**Comment by xiaoyu-ebox** [comment]
Thank you. I am very interested in this project.

**Pull request merged**
