### PR TITLE
Added functionalities and resolved some incidents

### PR DESCRIPTION
**Pull request by amerinoj**
This version fix the next issues

all.sh:
-	Now detect other wireless cards that are manager by wpa_supplicant.
 using a external dongle and when the wireless card is put in p2p mode the interface name is not change it, but we can use "iw dev type" to identify the mode.

D2.py:
- Add overload parameters  :
interface ip address
interface mask
interface name
neighbor peer address
	use:  d2.py -i "self_ip_address" -m  "mask" -d "device" -p "ip_peer_address "
This fix some problems, sometimes the connection tried to establish through another network card, now when the sock is created the interface name is passed to ensure the connection is open to the correct interface 

- Timeouts and payloads modified in the socket objects
The sockets has delimiter the timeout and the payload size these changes permit optimize the load and quality in the connection. Also when you press Ctr+^C or the System send a signal to close the proccess to shutdown the program can ear it and exit in correct order.

- Integrated DHCP server.
Now is not need use a external DHCP to assign Ip address to a peer neighbor. The code has integrate "dhcpserver.py" this is a modified version of "PyPXE" proyect.
https://github.com/pypxe/PyPXE
The original code was modified to assignen P2P addres "/30" and asing always the same address to diferents neigbors. 
This permit a exact control of address assigned and permit renew the leased time of dhcp servers.

The dhcpserver.py is controller by threading in main program.

-Catch exceptions
Now the code has a complete Catch exceptions and will finish right if a exception is detected. All sockets will be close and the all subprocess will be end

-Debug
level_name='info'
Implemented python logging. Now you can define the information level to debug the code, or put in "info" level to normal use.

-lazycast.service
As now the main program only management one connection per launch. 
The lazycast service restart the application when detect a exit code.
Restart=always
RestartSec=2s
lazycast.service was modified to intergrate the daemon  in the main systemctl.

- h264.c
Was suppressed the message "sound error " when only video is transmitter.

### CODE REVIEW

**Comment by homeworkc** [comment]
A loop may be needed in ``all.sh`` around ``d2.py`` to allow reconnection (after a connection is lost) or connections from other devices.
Line 42 and 43 in README might be unnecessary, since device_name is also set in ``all.sh``. (In the future tho, I might set the device_name to hostname because of the (possible) Miracast over infrastructure feature.)
In order to keep it SFW, I prefer ``31415926`` as the default pin.
If possible, the DEFINE THE INTERFACE section can be clearer. Perhaps include instructions for people who only use the built-in wifi chip. My goal is to make the instruction as easy as possible so that people relatively new to Pi and linux can simply copy the command and use it.
Line 314 in ``d2.py`` can be deleted.
Is there benefits to adopt a new dhcp server? At the moment we use udhcpd in busybox, which is already installed on most system and it works relatively well.
Have you tested on Raspbians with NetworkManager? In the past I have seen big improvements when NetworkManager is installed, although I am not sure whether it is true in your configuration. (I think the built-in network interface interferes with some of the p2p function. For example, if NetworkManager is used, the p2p-wlan0-0 interface can usually be created instantly without the need to loop a few times to create a new interface.)

**Comment by amerinoj** [comment]
-Added main loop in "all" file
-Yes you're right the lines 42 and 43 are suppress in the README.
-Pin code changed to 31415926 

I'll try update de definition interface secction or create a bash script to configure or install.

-  Line 314  deleted in d2.py. jeje . I didn't know if the line had any significat for you.

When I checked the ip address asigned by udchp saw the lease time asigned  is 24h and in some times the dhcp client no request  a new ip address. an other problem is when you disconnect the source and connect other the arp entry is cached is OS and  try to connect to incorrect mac address.


No i didn't tested with NetworkManager, but normaly you need disable the NetworkManager if you want self manager the interfaces. If use NetworkManager the service try to take the control over the interfaces configuration
See  :
https://linuxconfig.org/how-to-set-a-static-ip-address-on-debian-10-buster

this issue is common when use a program to control the interfaces state as airdump. always is recommend disable the networkmanager service. 
But this has a problem if you need use networkmanager to manager other interfaces. For these is important untherstand the secction " DEFINE THE INTERFACE  " to put "wpa_supplicant" or "nohook wpa_supplicant"

This post try to  explaint the older configuracion for Debian 'Wheezy'.  and the configuration need after  Debian 'Wheezy'. 
https://raspberrypi.stackexchange.com/questions/39785/differences-between-etc-dhcpcd-conf-and-etc-network-interfaces
after Debian 'Wheezy'.  the interfaces configuration is do it under /etc/dhcpcd.conf

**Comment by amerinoj** [comment]
I checked it the issues selection and some people has a problem with Pin Code and pairing . If the pin code is request all times or wlan adapter is no put in P2P mode maybe is because the /etc/wpasupplicant.conf need root priviligies to be edit and the  ".all" script is lauching under pi user.

I think is better run the ".all" with root privilegies.

**Comment by manjotsidhu** [comment]
@amerinoj I just now tested your changes and I am getting these errors:
```
Selected interface 'p2p-wlan0-0'
Available interfaces:
p2p-wlan0-0
p2p-dev-wlan0
wlan0
command failed: No such device (-19)
Selected interface 'p2p-wlan0-0'
OK
Selected interface 'p2p-wlan0-0'
OK
Selected interface 'p2p-wlan0-0'
OK
Selected interface 'p2p-wlan0-0'
OK
Selected interface 'p2p-wlan0-0'
OK
Selected interface 'p2p-wlan0-0'
OK
Selected interface 'p2p-wlan0-0'
OK
Selected interface 'p2p-wlan0-0'
OK


command failed: No such device (-19)
Selected interface 'p2p-wlan0-0'
FAIL
Selected interface 'p2p-wlan0-0'
Available interfaces:
p2p-wlan0-0
p2p-dev-wlan0
wlan0
command failed: No such device (-19)
Selected interface 'p2p-wlan0-0'
FAIL
Selected interface 'p2p-wlan0-0'
Available interfaces:
p2p-wlan0-0
p2p-dev-wlan0
wlan0
command failed: No such device (-19)
Selected interface 'p2p-wlan0-0'
FAIL
```

**Comment by amerinoj** [comment]
please show me these files outputs
iw dev wlan0  info
cat /etc/network/interfaces
cat /etc/dhcpcd.conf
cat /etc/wpa_supplicant/wpa_supplicant.conf
cat /etc/os-release

**Comment by manjotsidhu** [comment]
Now I have updated my `dhcpcd.conf`
Now my error looks like this:
```
Selected interface 'p2p-dev-wlan0'
Available interfaces:
p2p-dev-wlan0
wlan0
command failed: No such device (-19)
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
1	DIRECT-Ns	86:db:4c:12:98:91	[DISABLED][P2P-PERSISTENT]
=1	
command failed: No such device (-19)
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-wlan0-0'
Available interfaces:
p2p-wlan0-0
command failed: No such device (-19)
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-wlan0-1'
Available interfaces:
p2p-wlan0-1
command failed: No such device (-19)
Selected interface 'p2p-wlan0-1'
'P2P_GROUP_ADD persistent=1' command timed out.
```

iw dev wlan0 info
```
Interface wlan0
	ifindex 3
	wdev 0x1
	addr b8:27:eb:e1:5f:96
	ssid pi
	type managed
	wiphy 0
	channel 8 (2447 MHz), width: 20 MHz, center1: 2447 MHz
	txpower 31.00 dBm
```
cat /etc/network/interfaces
```
# interfaces(5) file used by ifup(8) and ifdown(8)

# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d
auto wlan0
iface wlan0 inet manual
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
```
cat /etc/dhcpcd.conf
```
# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Allow users of this group to interact with dhcpcd via the control socket.
#controlgroup wheel

# Inform the DHCP server of our hostname for DDNS.
hostname

# Use the hardware address of the interface for the Client ID.
clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
#duid

# Persist interface configuration when dhcpcd exits.
persistent

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
# Most distributions have NTP support.
option ntp_servers
# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate Stable Private IPv6 Addresses instead of hardware based ones
slaac private

# Example static IP configuration:
#static ip_address=192.168.0.111
#static routers=192.168.0.1
#static domain_name_servers=8.8.8.8

#static ip_address=192.168.5.5/24
#static ip6_address=fd51:42f8:caae:d92e::ff/64
#static routers=192.168.0.1
#static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1
#static domain_name_servers=192.168.0.1

# It is possible to fall back to a static IP if DHCP fails:
# define static profile
#profile static_eth0
#static ip_address=192.168.1.23/24
#static routers=192.168.1.1
#static domain_name_servers=192.168.1.1

# fallback to static profile on eth0
#interface eth0
#fallback static_eth0

interface wlan0
	wpa_supplicant

#interface p2p-wlan0-0
#	wpa_supplicant
```
cat /etc/wpa_supplicant/wpa_supplicant.conf
```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
device_name=DIRECT-raspberrypi
device_type=7-0050F204-1
p2p_go_ht40=1
country=IN

network={
	ssid="pi"
	psk="raspberry"
	key_mgmt=WPA-PSK
}

network={
	ssid="DIRECT-Ns"
	bssid=86:db:4c:12:98:91
	psk="9AGWt6jO"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	auth_alg=OPEN
	mode=3
	disabled=2
}

network={
	ssid="DIRECT-Ns"
	bssid=b2:ad:99:16:a9:a0
	psk="9AGWt6jO"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	auth_alg=OPEN
	mode=3
	disabled=2
}
```
cat /etc/os-release
```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by amerinoj** [comment]
in cat /etc/network/interfaces
you should have only
''''
# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d
'''

/etc/dhcpcd.conf look like fine

cat /etc/wpa_supplicant/wpa_supplicant.conf
put only 
'''
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
device_name=DIRECT-raspberrypi
device_type=7-0050F204-1
p2p_go_ht40=1
country=IN
''
try check these changes, if not work i'll  check tomorrow in a clean install .

**Comment by manjotsidhu** [comment]
I have tried all these above changes, still the same issue for me.

**Comment by manjotsidhu** [comment]
I have tried all these above changes, still the same issue for me.

**Comment by amerinoj** [comment]
you are right.
the all.sh had some problems to detect correctly the virtual p2p interfaces when  wlan0 is use.

I did big modifications in the code ("all.sh") and was check it in a clean install.
I think now is working fine to any wireless interface.
I have remove the main while loop because when you try to close or shutdown the machine don't stop.

I created a install bash to easy instalation.

Please test the new code and giveme your feedback.

**Comment by manjotsidhu** [comment]
```
configuring WPA_supplicant
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
FAIL
Selected interface 'p2p-dev-wlan0'
Connected to interface 'wlan0.
2	DIRECT-PR	1e:8e:9d:20:e9:41	[DISABLED][P2P-PERSISTENT]
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-wlan0-56'
FAIL
Device error:p2p-dev-wlan0
./all.sh: line 61: break: only meaningful in a `for', `while', or `until' loop
WPA config in P2P mode
p2p-dev-wlan0
SIOCSIFADDR: No such device
p2p-dev-wlan0: ERROR while getting interface flags: No such device
SIOCSIFNETMASK: No such device
The display is ready
Your device is called: DIRECT-raspberrypi
PIN-->
31415926<--PIN
Waiting connection
[INFO] LazyCast Level output:20
[INFO] LazyCast DHCP Server IP: 192.168.173.1
[INFO] LazyCast Lease Range: 192.168.173.2 - 192.168.173.2
[ERROR] LazyCast  ERROR socket.error
[INFO] LazyCast  Exit
[INFO] LazyCast Stoping DHCP SERVER:True
Connection Finished
Selected interface 'p2p-dev-wlan0'
OK
```

**Comment by amerinoj** [comment]
if you see 
[ERROR] LazyCast  ERROR socket.error
mean the .all.sh is no run as root. Please run .all.sh as root.

**Comment by manjotsidhu** [comment]
Now
```
configuring WPA_supplicant
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
FAIL
Selected interface 'p2p-dev-wlan0'
Connected to interface 'wlan0.
2	DIRECT-PR	1e:8e:9d:20:e9:41	[DISABLED][P2P-PERSISTENT]
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-wlan0-0'
FAIL
Device error:p2p-dev-wlan0
```

**Comment by amerinoj** [comment]
please add "set -x" after "#!/bin/bash +x "in ".all.sh" to trace the problem
```
#!/bin/bash +x
set -x
```
your interface no comming up when 
execute wpa_cli p2p_group_add persistent$perstr
I don't know why , maybe the distro version? my distribution is  "raspbian buster"

**Comment by manjotsidhu** [comment]
Same issue, my `wpa_supplicant.conf` is always clear when running but `all.sh` automatically adds `DIRECT-XX`
Moreover, I prefer to be connected to my WiFi as it was before.
```
+ pin=31415926
+ ip_neighbor=192.168.173.2
+ ip_interface=192.168.173.1
+ mask=255.255.255.252
+ select_interface=wlan0
+ '[' 0 -ne 0 ']'
++ wpa_cli status
+ [[ Selected interface 'p2p-dev-wlan0'
wpa_state=DISCONNECTED
p2p_device_address=de:3d:32:77:a8:9a
address=de:3d:32:77:a8:9a
uuid=6c54a807-9c28-5a89-9941-1cc403df5ff5 != *\w\p\a\_\s\t\a\t\e\=\C\O\M\P\L\E\T\E\D* ]]
+ echo 'configuring WPA_supplicant'
configuring WPA_supplicant
+ wpa_cli set p2p_go_ht40 1
Selected interface 'p2p-dev-wlan0'
OK
+ wpa_cli p2p_find type=progessive
Selected interface 'p2p-dev-wlan0'
OK
++ uname -n
+ wpa_cli set device_name DIRECT-raspberrypi
Selected interface 'p2p-dev-wlan0'
OK
+ wpa_cli set device_type 7-0050F204-1
Selected interface 'p2p-dev-wlan0'
OK
+ wpa_cli set p2p_go_ht40 1
Selected interface 'p2p-dev-wlan0'
OK
+ wpa_cli wfd_subelem_set 0 000600111c44012c
Selected interface 'p2p-dev-wlan0'
OK
+ wpa_cli wfd_subelem_set 1 0006000000000000
Selected interface 'p2p-dev-wlan0'
OK
+ wpa_cli wfd_subelem_set 6 000700000000000000
Selected interface 'p2p-dev-wlan0'
OK
++ wpa_cli interface wlan0
+ ain='Selected interface '\''p2p-dev-wlan0'\''
Connected to interface '\''wlan0.'
+ echo 'Selected interface '\''p2p-dev-wlan0'\''
Connected to interface '\''wlan0.'
Selected interface 'p2p-dev-wlan0'
Connected to interface 'wlan0.
++ echo 'Selected interface '\''p2p-dev-wlan0'\''
Connected to interface '\''wlan0.'
++ grep Selected
+ select='Selected interface '\''p2p-dev-wlan0'\'''
++ echo Selected interface ''\''p2p-dev-wlan0'\'''
++ cut '-d'\''' -f2
+ interface=p2p-dev-wlan0
++ wpa_cli list_networks
++ tail -1
++ grep '\[DISABLED\]\[P2P-PERSISTENT\]'
+ perentry=
+ echo ''

++ echo ''
++ grep -c P2P-PERSISTENT
+ '[' 0 -gt 0 ']'
+ perstr=
+ wpa_cli p2p_group_add persistent
Selected interface 'p2p-dev-wlan0'
OK
++ iw dev p2p-dev-wlan0 info
+ [[ command failed: No such device (-19) == *\N\o\ \s\u\c\h\ \d\e\v\i\c\e* ]]
+ wpa_cli p2p_group_add persistent
Selected interface 'p2p-wlan0-0'
FAIL
+ sleep 2
++ iw dev p2p-dev-wlan0 info
+ [[ command failed: No such device (-19) == *\N\o\ \s\u\c\h\ \d\e\v\i\c\e* ]]
+ echo Device error:p2p-dev-wlan0
Device error:p2p-dev-wlan0
+ exit
```

**Comment by amerinoj** [comment]
Now all.sh work with internal wireless card witout persistance and  work with external wifi dogle with persistance.
Fixed all.sh to mitigate the random mac-address in p2p-device. 

I reviewed the code and if wlan0 is used to put the interface in p2p-go the only method is create a virtual-dev from main wlan0"managed"

 iw list | grep "P2P-GO\|phy0"
```
Wiphy phy0
                 * P2P-GO
                 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * #{ managed } <= 1, #{ P2P-device } <= 1, #{ P2P-client, P2P-GO } <= 1,
```

when wpa_supplicant create the virtual interface p2p-device isn't specified the mac-address or use mac address randomizer method.

every time wpa_supplicant is reload the "p2p-device" mac address is changed
iw dev
```
phy#0
        Unnamed/non-netdev interface
                wdev 0x8
                addr a2:8b:7f:d5:9f:f7
                type P2P-device
                txpower 31.00 dBm
        Interface wlan0
                ifindex 3
                wdev 0x1
                addr b8:27:eb:06:c2:47
                type managed
                channel 1 (2412 MHz), width: 20 MHz, center1: 2412 MHz
                txpower 31.00 dBm
```

if stop the wpa_supplicant and create the p2p-device manually is posible specifed the mac-address
```
iw dev wlan0 interface add p2p-dev-wlan0 type __p2pdev addr b8:27:eb:06:c2:ab
iw dev wlan0 interface add p2p-go-wlan0 type __p2pgo addr b8:27:eb:06:c2:aa
```
so i think the problem is in wpa_supplicant.

reviewing the parameters permitted in wpa_supplicant i found the next parameters but are ignored by wpa_supplicant
```
p2p_device_persistent_mac_addr=26:b1:ae:13:c1:d5
p2p_device_random_mac_addr=0
p2p_interface_random_mac_addr=0
```
well, I could not fix the persistent mac-address problem for wlan0, but the rest of features work fine

**Comment by manjotsidhu** [comment]
Now tested the latest changes now. this is on the first launch :
```
pi@raspberrypi:~/test/lz-pull $ sudo ./all.sh
Selected interface 'p2p-dev-wlan0'
Connected to interface 'wlan0.
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
configuring WPA_supplicant
No found P2P network 
Creating new ...
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-wlan0-0'
OK
Selected interface 'p2p-wlan0-0'
OK
Selected interface 'p2p-wlan0-0'
OK
Interface UP:p2p-wlan0-0  in P2P mode
WPA config in P2P mode
p2p-wlan0-0
The display is ready
Your device is called: DIRECT-raspberrypi
PIN-->
'WPS_PIN any 31415926' command timed out.
<--PIN
Waiting connection
[INFO] LazyCast Level output:20
[INFO] LazyCast DHCP Server IP: 192.168.173.1
[INFO] LazyCast Lease Range: 192.168.173.2 - 192.168.173.2
[ERROR] LazyCast  ERROR socket.error
[INFO] LazyCast  Exit
[INFO] LazyCast Stoping DHCP SERVER:True
Connection Finished
```

And this on the second launch.
```
pi@raspberrypi:~/test/lz-pull $ sudo ./all.sh
Selected interface 'p2p-dev-wlan0'
Connected to interface 'wlan0.
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-dev-wlan0'
OK
configuring WPA_supplicant
Previous net_id Found...
Previous net_id Found: 0
Selected interface 'p2p-dev-wlan0'
OK
Selected interface 'p2p-wlan0-1'
OK
Selected interface 'p2p-wlan0-1'
OK
Selected interface 'p2p-wlan0-1'
'WFD_SUBELEM_SET 6 000700000000000000' command timed out.
Device error:p2p-dev-wlan0
```

**Comment by amerinoj** [comment]
netstat -aptn | grep :53

**Comment by amerinoj** [comment]
Hi,
The error 
```
[ERROR] LazyCast  ERROR socket.error
```
usually be appear whe exists another program using the port 53 in the interface , check if you haven't dnsmasq or udhcp running in the same interface .

use " netstat -aptn | grep :53 " to check it.

The second error maybe is because the  previous instance no closed well .

if appear again check if the last intance is close it.
```
ps -aux | grep d2.py
```

**Comment by homeworkc** [comment]
I really appreciate your contribution. I did some testing and after some extensive modification I can get your commit to work. However, I think I prefer the current branch (udhcpd and NetworkManager) for the following reason:
1. It is simpler to assign the same IP to different devices. Otherwise, the Python script would have to poll and try to connect to every IP. The current branch also works in the case of switching multiple devices within a short time. The only glitch is that sometimes the p2p-wlan0-0 gets removed after disconnection, but the patch for this is more easily fixed in the current branch.
2. The current branch detects and setup the p2p interface more easily, at least for the case of using the built-in wifi, which should be the majority of the use case. The built-in wifi can also simultaneously connect to the Internet and run lazycast. In fact, I did a test where chromium is playing youtube HD video in the background while lazycast is running in the foreground. With NetworkManager, I didn't experience any glitch at all. Even the audio are mixed correctly.

I tried merging two branches for a long time but I couldn't figure out a good way to do it, so I will leave all.sh and d2.py as is for the time being. Right now I want to focus on implementing MICE (I think I know the solution for the most part and the only thing left is the mdns implementation) or improving the uibc part (adopting the mouse/keyboard input from [freerdp](https://github.com/FreeRDP/FreeRDP/blob/6313cccb6e51910fcd1d5d7771c40314347db536/client/X11/xf_window.c)). I might go back and try to merge the two branches in the future.

**Pull request closed without merging**
